import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import ButtonAppBar from "@/app/components/app-bar";
import { Box } from "@mui/material";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <Box sx={{ bgcolor: "rgba(237, 230, 212, 0.5)" }}>

            <ThemeProvider theme={theme}>
              <ButtonAppBar></ButtonAppBar>
              {children}
              <Footer />
            </ThemeProvider>
          </Box>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
